### ISSUE TITLE
Transparently running dve when ffmpeg is executed?

### ISSUE THREAD

**Issue by Red5d** [nergdron/dve#5]
Is it possible to make this into a script that can act like ffmpeg and take ffmpeg commandline options? 

I'm working with a tool that uses ffmpeg behind the scenes and it would be great if I could use this to easily distribute the ffmpeg processes run by that tool.

**Comment by nergdron** [comment]
I think this should be possible for things like encoding options, but given how it currently chops up files for encoding, stuff like clipping the source file and stuff likely won't work properly. I'll give it some thought.

**Comment by nergdron** [comment]
I don't think this is gonna be doable, closing.
