### ISSUE TITLE
Gaps between segments

### ISSUE THREAD

**Issue by cowai** [nergdron/dve#9]
Hi,
I have tested several video codecs and containers and all of them has short gaps around the segment split time.
I am using ffmpeg 3.1.4 static build.
Is there specific version known to work?

**Comment by paulm17** [comment]
I know this is an old issue, but was there any resolution?

The following is what I have been attempting and no matter what I do, whenever I encounter the stitch, I get a slight audio delay.  

If you overcame this issue, I'd love to know about it.

I'm using ffmpeg 4.2.0 manual build.

Thanks

-------

	ffmpeg -i test.mp4 -f segment -segment_time 150 -c copy -map 0 -copyts -muxdelay 0 -reset_timestamps 1 test_%03d.ts &&

	for i in test_*.ts;
	  do name=`echo $i | cut -d'.' -f1`;
	  echo $name;
	  ffmpeg -i "$i" -codec:v libx264 -codec:a aac -copyts -threads 6 "t_${name}.ts"
	done &&

	ls -v t_test*.ts | xargs cat | ffmpeg -i - -c copy -movflags faststart output.mp4

**Comment by cowai** [comment]
@paulm17 Thanks. I have a similiar fix for this. I first just render without sound, and then finally I just add the audio from the source file as a final job.
